debug: true
sources:
  unsplash-access: ${UNSPLASH}
  openai:
    model: gpt-3.5-turbo
    url: https://api.openai.com/v1/chat/completions
    key: ${OPENAI}
spring:
#  sql:
#    init:
  #      platform: postgresql
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://mouse.db.elephantsql.com:5432/kjkeghdw
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR