name: Test, Build And Deploy Application
on:
  push:
    branches:
      - "main"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_WEBAPP }}
      - name: Setup jdk-17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean package
      - name: Azure CLI script file
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az group list --output=table
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: kikkersANDmonstersB
          package: target/*.jar
      # Azure logout
      - name: logout
        run: |
          az logout